version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ${NGINX_HOST}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - stylish-net

  redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    volumes:
      - ./volumes/redis/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - stylish-net
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PASSWORD}
    ports:
      - ${CACHE_PORT}:${CACHE_PORT}
    env_file:
      - .env

  api: 
    image: ${API_IMAGE}
    container_name: ${API_HOST}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - stylish-net

networks:
  stylish-net:
    driver: bridge