name: Stylish-CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Building Docker image..."
          docker build -t chiehyu914/stylish-cowork:latest . --file server/Dockerfile --no-cache --platform linux/amd64
          echo "Logging in to Docker Hub..."
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          echo "Pushing Docker image to Docker Hub..."
          docker push chiehyu914/stylish-cowork:latest

  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_TARGET_DIR }}
            docker pull chiehyu914/stylish-cowork:latest
            docker compose --env-file etc/app.env down
            docker compose --env-file etc/app.env up -d
            docker compose --env-file etc/app.env ps
